php-tmdb/api

- lib/Tmdb/Factory/TvFactory.php
- lib/Tmdb/Model/Tv.php
> Person and tv related issues

- composer.json
- examples/find/api/get.php
- examples/find/model/get.php
- lib/Tmdb/Api/Find.php
- lib/Tmdb/ConfigurationInterface.php
- lib/Tmdb/Event/HydrationSubscriber.php
- lib/Tmdb/Event/RequestSubscriber.php
- lib/Tmdb/Exception/TmdbApiException.php
- lib/Tmdb/Factory/Common/VideoFactory.php
- lib/Tmdb/Factory/FindFactory.php
- lib/Tmdb/Factory/People/CastFactory.php
- lib/Tmdb/Factory/People/CrewFactory.php
- lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php
- lib/Tmdb/HttpClient/HttpClient.php
- lib/Tmdb/Model/Account/ListItem.php
- lib/Tmdb/Model/Collection.php
- lib/Tmdb/Model/Common/AccountStates.php
- lib/Tmdb/Model/Query/Discover/DiscoverMoviesQuery.php
- lib/Tmdb/Model/Tv.php
- lib/Tmdb/Model/Tv/Episode.php
- lib/Tmdb/Repository/FindRepository.php
- lib/Tmdb/Repository/MovieRepository.php
- lib/Tmdb/Repository/SearchRepository.php
- lib/Tmdb/Repository/TimezoneRepository.php
- test/Tmdb/Tests/Repository/FindRepositoryTest.php
> Scrutinizer issues

- lib/Tmdb/HttpClient/HttpClient.php
- test/Tmdb/Tests/HttpClient/HttpClientTest.php
Useful when you'd like to remove a plugin after adding it.
> Add a removeSubscriber method to the HttpClient

- lib/Tmdb/Client.php
OptionsResolver::setAllowedTypes method with an array of options is deprecated since version 2.6 and will be removed in 3.0. Updated to use the new signature with a single option instead.
> Update setAllowedTypes in Client to use new signature

- lib/Tmdb/Model/Person/MovieCredit.php
Hi,
I found a bug when I use the PeopleRepository like:
```
$person= new PeopleRepository()->load(1100); //ex. Arnold Schwarzenegger
```
and then want to get the movies where this person was in crew like:
```
$person $person->getMovieCredits()->getCrew();
```
I got a list of MovieCredit (I suppose this is a common Object to contain both, Cast and Crew Credits) which have no properties for job and departments.
This Pull Request just fix this.
> Bugfix: MovieCredit must have Job and Department to fetch all info

- composer.json
Using an empty namespace prefix is bad for performance, see `composer validate --strict`.
> Use TMDB namespace prefix in psr-4 autolaoder

- .travis.yml
- composer.json
I'd like to use this library in a Symfony 3, PHP 7 project. This changeset allows Symfony 3 components to be installed, tests Symfony 2.4/2.6 through 3.0 and requires that the tests pass for PHP 7.
> Test support for Symfony 2.4/2.6 through 3.0 and require support of PHP 7

- .travis.yml
I was checking an earlier version that used the `$SYMFONY_VERSION` environment variable. Result: the library wasn't actually tested against the given versions. :sweat_smile:  After merging this commit, it will be. And no breakage :clap:
> Check correct Symfony component version environment variables

- examples/genres/api/allmovies.php
- examples/genres/api/alltv.php
- examples/genres/model/allmovies.php
- examples/genres/model/alltv.php
- lib/Tmdb/Api/Genres.php
- lib/Tmdb/Repository/GenreRepository.php
- test/Tmdb/Tests/Api/GenresTest.php
- test/Tmdb/Tests/Repository/GenreRepositoryTest.php
I encountered two new endpoints for genres while trying to import genres into my project. They have split the available genres between movies and TV shows. This commit allows for these two new endpoints to be accessed.
http://docs.themoviedb.apiary.io/#reference/genres/genremovielist/get
http://docs.themoviedb.apiary.io/#reference/genres/genretvlist/get
> Add new Genre API endpoints.

- lib/Tmdb/Api/Search.php
- test/Tmdb/Tests/Api/SearchTest.php
- test/Tmdb/Tests/Repository/SearchRepositoryTest.php
Hello,
Testing the search API, I discovered that the URL encoding happened twice: on TMDB API side first, and then Guzzle does it again.
This is not an issue in many cases, but if you start dealing with accents it makes TMDB unable to return any result.
I have forked and fixed the issue on my side. Thought it could be of an interest to you.
> Remove urlencode in search API to prevent double encoding

- lib/Tmdb/Exception/TmdbApiException.php
- lib/Tmdb/HttpClient/Adapter/AbstractAdapter.php
- lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php
- test/Tmdb/Tests/HttpClient/Adapter/GuzzleAdapterTest.php
Closes #118 
- `AbstractAdapter` will no longer fail for unexpected body content.
- `NullException` error is now thrown for all 500 response codes. (these response contain HTML body, but no JSON). So I figure `NullException` was more consistent than using `TmdbApiException`
- Adds unit test for server 500 errors.
> Throws NullException for response codes of 500

- lib/Tmdb/Repository/TvEpisodeRepository.php
- lib/Tmdb/Repository/TvSeasonRepository.php
- test/Tmdb/Tests/Repository/TvEpisodeRepositoryTest.php
- test/Tmdb/Tests/Repository/TvSeasonRepositoryTest.php
Episode and Season API use the Season Number and Episode Number and not their id to fetch data. 
Also changed the check with the is_null function in the load function as there is a chance
that there is a Season 0 for a TV Show. When the Season is 0 then the
$season == null returns true.
> Fixed Episode and Season Repositories

- README.md
@wtfzdotnet @MarkRedeman This ")" is not needed, right?
> Fixed syntax errors in readme examples

- README.md
The middleware has changed with 2.1 where Guzzle 6 is using `guzzle-cache-middleware` now. I was getting an error using the `ArrayCache()` example, but wrapping the object in `new DoctrineCacheStorage(new ArrayCache())` fixed the issue.
The new cache objects have to have the interface from the `guzzle-cache-middleware` project.
> Update example for using the ArrayCache

- lib/Tmdb/Factory/PeopleFactory.php
- lib/Tmdb/Model/Person/Credit.php
- lib/Tmdb/Model/Tv.php
I had the Problem, when loaded a person, the credits would not be filled up correctly.
especially the tv show data can not be set on the credit:
hope this PR helps.
> Add properties of tv shows to MovieCredit and name it more generic

- README.md
- examples/caching.php
- lib/Tmdb/Client.php
- lib/Tmdb/HttpClient/HttpClient.php
- test/Tmdb/Tests/TestCase.php
This should fix php-tmdb/symfony#17
> Small improvement to make api usable by the bundle

- .travis.yml
- README.md
- composer.json
* Add symfony 3.1+ and php 7.1 to matrix
* Use phpunit installed locally by composer instead of global
* Add phpunit 4.8 to version constraint
phpunit ^5.0 requires php 5.6+, so tests for php 5.4 and 5.5 are failing. As branch '2.0' claims to support php 5.4+ - add phpunit 4.8 to allow test running on php runtimes <5.6
* Update README
Add php 7.1 to the list of runtimes, get rid of 'Symfony2' naming - use versionless 'Symfony' instead, formatting adjustments
> Add phpunit 4.8 to test branch '2.0' on php <5.6

- lib/Tmdb/HttpClient/HttpClient.php
As of https://github.com/rtheunissen/guzzle-log-middleware/issues/3 fixes https://github.com/php-tmdb/laravel/issues/31
> Fixes issue with logger level resolver name collision

- test/Tmdb/Tests/Model/Movie/ReleaseDateTest.php
When the tests run in an environment which is not in UTC timezone, one test case fails because the timezone is not set explicitly.
> Fix tests for non-UTC environments

- lib/Tmdb/Factory/ImageFactory.php
- test/Tmdb/Tests/Factory/ImageFactoryTest.php
- test/Tmdb/Tests/Resources/images/tagged_image.json
This patch fixes the issue described in #146. Now `createMediaImage()` just creates a generic image when no type is set explicitly. In addition, the hydration was done twice before (which might lead to overwritten data) and is now fixed as well.
> Fix tagged images

- lib/Tmdb/Client.php
- lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php
- lib/Tmdb/HttpClient/HttpClient.php
- test/Tmdb/Tests/ClientTest.php
- test/Tmdb/Tests/TestCase.php
This patch restores the way paths are stored in `Tmdb\HttpClient\Request`. The base URL is no longer part of the path and is passed to the HTTP adapter as part of the options bag (fixes #145).
Note: Custom HTTP adapters which do not follow the [documented](https://github.com/php-tmdb/api/blob/49896c9dfac88f859faedd7d1601a6d68e5d28cb/lib/Tmdb/Client.php#L172-L173) practice will probably break after applying this change.
> Pass relative path to HTTP adapters

- lib/Tmdb/Client.php
- lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php
- lib/Tmdb/HttpClient/HttpClient.php
- test/Tmdb/Tests/ClientTest.php
- test/Tmdb/Tests/TestCase.php
This is a follow-up #149 for `2.0` branch, quote from the initial PR:
> This patch restores the way paths are stored in `Tmdb\HttpClient\Request`. The base URL is no longer part of the path and is passed to the HTTP adapter as part of the options bag (fixes #145).
> 
> Note: Custom HTTP adapters which do not follow the [documented](https://github.com/php-tmdb/api/blob/2.0/lib/Tmdb/Client.php#L172-L173) practice will probably break after applying this change.
> Pass relative path to HTTP adapters, 2.0 branch

- lib/Tmdb/HttpClient/Adapter/GuzzleAdapter.php
This is a follow-up to #155 - retry after 1 second by default in case of retry and 429 response header has Retry-After=0
> Set Retry-After to be one second by default in case of retries

- README.md
Recently <http://hhvm.h4cc.de> went down causing glitches in README. The link, however, left intact.
> Fix faulty hhvm status badge

- composer.json
There does not seem to be any BC break that affects php-tmdb. The only
documented BC break is here:
https://github.com/Kevinrob/guzzle-cache-middleware/pull/75
> Allow kevinrob/guzzle-cache-middleware 2

- .travis.yml
- composer.json
Fortunately, no BC breaks occured in the two components such that the changeset is quite small.
> Allow Symfony 4 components
